---
- name: Create Service Nomad File
  template:
    src: nomad.service.j2
    dest: "/etc/systemd/system/nomad.service"
    owner: root
    group: root
    mode: 0644

- name: Create Nomad Daemon Directory
  file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad
    mode: 0755
